export enum ErrorCode {
  // Authentication Errors (AUTH_XXX)
  AUTH_UNAUTHORIZED = 'AUTH_001',
  AUTH_INVALID_TOKEN = 'AUTH_002',
  AUTH_TOKEN_EXPIRED = 'AUTH_003',
  AUTH_MISSING_CREDENTIALS = 'AUTH_004',
  AUTH_INVALID_CREDENTIALS = 'AUTH_005',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_006',
  AUTH_USER_DISABLED = 'AUTH_007',

  // System/General Errors (SYS_XXX)
  SYS_INTERNAL_ERROR = 'SYS_001',
  SYS_SERVICE_UNAVAILABLE = 'SYS_002',
  SYS_EXTERNAL_SERVICE_TIMEOUT = 'SYS_003',
  SYS_VALIDATION_FAILED = 'SYS_004',
  SYS_NOT_FOUND = 'SYS_005',
  SYS_FORBIDDEN = 'SYS_006',
  SYS_BAD_REQUEST = 'SYS_007',
  SYS_RATE_LIMIT_EXCEEDED = 'SYS_008',
  SYS_CONFLICT = 'SYS_009',
  SYS_UNSUPPORTED_MEDIA_TYPE = 'SYS_010',
  SYS_PAYLOAD_TOO_LARGE = 'SYS_011',

  // User Errors (USER_XXX)
  USER_NOT_FOUND = 'USER_001',
  USER_ALREADY_EXISTS = 'USER_002',
  USER_INVALID_DATA = 'USER_003',

  // Stellar/Blockchain Errors (STEL_XXX)
  STEL_WALLET_NOT_FOUND = 'STEL_001',
  STEL_INSUFFICIENT_FUNDS = 'STEL_002',
  STEL_TRANSACTION_FAILED = 'STEL_003',
  STEL_INVALID_ADDRESS = 'STEL_004',

  // News & Analytics Errors (ANLY_XXX)
  ANLY_SENTIMENT_ANALYSIS_FAILED = 'ANLY_001',
  ANLY_NEWS_SYNC_FAILED = 'ANLY_002',
  ANLY_DATA_NOT_FOUND = 'ANLY_003',
}
